### ISSUE TITLE
Word-pair visualization in Docker doesn't work!?

### ISSUE THREAD

**Issue by linas** [opencog/cogprotolab#5]
Hi @contrast-zone -- I created a Docker container that can digest any text files to count word-pairs, and then to use cogprotolab to visualize the results.  Everything works, except the visualizer itself, and there isn't any error strings or diagnostics that I can find.  I just get the  top word, and then `####ERROR####`.

The Docker is here: https://github.com/opencog/docker/tree/master/opencog/lang-pairs -- If you follow the instructions, it will work, right up to the visualization part. For most collections of text, it will fit in about 6GB RAM (not counting apache and docker itself, so maybe 10 GB RAM for system total!?)

I wanted to demo this to someone ...

**Comment by contrast-zone** [comment]
Hi @linas, I'll take a look.

**Comment by linas** [comment]
It's probably because I have PHP misconfigured in the Docker container.

BTW, in `telnet.php` if you say `scm quiet\n` then it won't sent the prompt string.

**Comment by linas** [comment]
I am narrowing it down. The `telnet.php` socket read is not working -- it does get the correct response, but times out of the loop, waiting for something more.

**Comment by contrast-zone** [comment]
It could be scm prompt. `get-prompt.php` returns the current prompt string as the last item in an array. Afterwards, the `telnet.php` returns as soon as it encounters the prompt. If there is a prompt mismatch, it times out.

**Comment by linas** [comment]
Its a missing newline. This fixes the timeout:
```
--- a/vis-word-pairs/fract.html
+++ b/vis-word-pairs/fract.html
@@ -573,7 +573,7 @@
                             query += ")";
                         query += ")";
                         
-                        sendcmd (query + "\n").then (
+                        sendcmd (query + "(newline)\n").then (
                             (response) => {
                                 // stats
                                 try {
```

It then returns valid data from telnet.php ....  But it still doesn't display.

**Comment by linas** [comment]
parser.parse throws: `TypeError: txt.substr is not a function`

**Comment by contrast-zone** [comment]
It must be that a different prompt from usual one causes the mess. Could you try to setup scm to have the same prompt we had a half year ago?

**Comment by contrast-zone** [comment]
also, `get-prompt.php` waits for 1 second before it returns the prompt. If the prompt doesn't return in a second, it gets lost.

It is in `get-prompt.php` on line 25:
```
$delay = 1;
```
Maybe to set it up for a longer time?

**Comment by linas** [comment]
I don't think the prompt is the problem. With the above diff, the `src/telnet.php` now returns the correct data, but the parser throws that `TypeError` ...

(Anyway, I don't remember the old prompt; prompts are user-configurable.  FYI, since this summer, there is now also a websockets interface, default at port 18000 but ...Hmmm. But that won't actually help :-/)

**Comment by contrast-zone** [comment]
Give me a day, I'll try to setup the environment on my machine after upgrading it to 12 GB. Currently I'm on 4 GB, but I must have some spare 8 GB somewhere around.

**Comment by linas** [comment]
Well, it might run in 4GB. You might get lucky. 

I now see that the `TypeError: txt.substr is not a function` error is not being thrown by the parser, but by `fract.html`  when it works with the parser results. ...

**Comment by linas** [comment]
> it might run in 4GB. You might get lucky.

I mean, 4 years ago, someone got the atomspace working on a 2GB raspberry PI. That included all of ROS for robot control. So I am not sure what is making everything so fat.

**Comment by contrast-zone** [comment]
`txt` is obviously not a string while it should be.

**Comment by linas** [comment]
Yes, I see now. the cogserver is returning `(WordNode "foo" (ctv 1 0 54))`  and your parser is expecting just plain `(WordNode "foo")`. As a result, at line 611, txt is an array, instead of a string.  Also at line 616

**Comment by linas** [comment]
So, part two of the fix is this:
```
--- a/vis-word-pairs/fract.html
+++ b/vis-word-pairs/fract.html
@@ -607,12 +607,14 @@
             function setChildren (data, rel) {
                 var ret = [];
                 while (Array.isArray(rel[2])) {
-                    var txt = rel[0][1][1][2];
+                    var txta = rel[0][1][1][2];
+                    var txt = txta[0];
                     ret.push (txt.substr (1, txt.length - 2));
                     rel = rel[2];
                 }
                 
-                var txt = rel[1][1][2];
+                var txta = rel[1][1][2];
+                var txt = txt1[0];
                 ret.push (txt.substr (1, txt.length - 2));
 
                 data.children = [];
```

After this, the bubbles do fill out to the first level.  After that, there are more errors, because somehow the query is broken for the next level down.

**Comment by contrast-zone** [comment]
Function `setChildren` is getting a sub-array of what it should get. Can you try to trace back from where `setChildren` is called? `rel[0]` should hold the head child while `rel[2]` should hold the tail children. And that should recurse all the way down until rel[2] is not an array anymore.

**Comment by contrast-zone** [comment]
The leaves of array are arrays while they should be strings. The chances are that the query output changed since my last intervention.

**Comment by linas** [comment]
> After that, there are more errors

The third set of errors was a bug in my code; I just now pushed a fix: 0152d98e5dbf45cd4a3ccea4c70d441f2f0f5ce1

So that leaves the setChildren issue.

> The chances are that the query output changed since my last intervention.

Well, it is almost surely because the returned output is `(WordNode "foo" (ctv 1 0 54))` instead of `(WordNode "foo")`  In general, the output might be with or without the `(ctv... stuff)` or `(stv...)` stuff, or similar; that depends on atomspace data.   Thus, I think the final fix would need to be javascript that says  "if txta is an array then txt=txta[0] else txt=txta"  I'm terrible with javascript but I will try to figure that out.

**Comment by linas** [comment]
OK, I opened pull req #6 and it appears to "work for me" -- it fixes everything -- Could you review it and merge it, if it looks good to you? Else provide something different or better?

**Comment by contrast-zone** [comment]
So, children are shown all the way down, right?

**Comment by linas** [comment]
Yes, now they are!

**Comment by linas** [comment]
BTW, I'm starting to like your visualizer a bit more; making the traversals "linear" does simplify a lot of conceptual issues...

**Comment by contrast-zone** [comment]
> Yes, now they are!

Ok, merging...

> BTW, I'm starting to like your visualizer a bit more; making the traversals "linear" does simplify a lot of conceptual issues...

Thanks.

Let me know if there is anything else.
